# Environment variable
export SLACK_OUTGOING="YOUR_SLACK_TOKEN"
export SLACK_INCOMING="YOUR_SLACK_HOOK"
export SLACK_CHANNEL="YOUR_SLACK_CHANNEL"

export MM_OUTGOING="YOUR_MM_TOKEN"
export MM_INCOMING="YOUR_MM_HOOK"
export MM_CHANNEL="YOUR_MM_CHANNEL"

export MMSLACK_PORT=YOUR_LISTENING_PORT

# Run server
node mm2slack.js
